[package]
name = "dixxxie"
authors = ["smokingplaya", "serenitymc"]
version = "0.1.12"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
dotenv = "0.15.0"
env_logger = "0.11.6"
r2d2 = "0.8.10"

[dependencies.serde]
version = "1.0.217"
features = ["derive"]

[dependencies.diesel]
version = "2.2.0"
features = ["postgres", "r2d2"]

[dependencies.redis]
version = "0.28.1"
features = ["r2d2"]

[dependencies.axum]
version = "0.8.1"
features = ["macros"]